### ISSUE TITLE
Path Traversal Vulnerability

### ISSUE THREAD

**Issue by OsandaMalith** [nolimits4web/Framework7-Website#18]
Have a look in here, view source. file_get_contents() is used.
http://www.idangero.us/framework7/plugins/feeds/demo/proxy.php?url=proxy.php

Anyone can read any file in your server, for example:

> hidden

**Comment by nolimits4web** [comment]
Thanks, will fix it

**Comment by OsandaMalith** [comment]
Welcome, if you acknowledge me let me know!

**Comment by nolimits4web** [comment]
Seems to be fixed now

**Comment by OsandaMalith** [comment]
Is it alright if I disclose this now?

**Comment by nolimits4web** [comment]
give me few days to do more tests with it, i will let you know

**Comment by OsandaMalith** [comment]
alright :+1:

**Comment by nolimits4web** [comment]
Sorry, forgot to say. You can disclose this
